name: test_sodre
description: Sodré Santoro Test.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bloc: ^8.1.1
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_modular: ^5.0.3
  path: ^1.8.2
  sqflite: ^2.2.8+4
  validatorless: ^1.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
